// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum LogisticActionType {
  INJECT,
  TRANSFER,
  EXTRACT
}

enum LogisticTransactionType {
  WITHDRAWAL,
  DEPOSIT
}
