// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum LogisticDepotType {
  COLD,
  WARM,
  HOT
}

enum LogisticConstraintType {
  EQUAL,
  ABOVE,
  BELOW
}

enum LogisticActionType {
  INJECT,
  TRANSFER,
  EXTRACT
}

enum LogisticTransactionType {
  WITHDRAWAL,
  DEPOSIT
}
