// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LogisticNetwork, LogisticNetworkData } from "./tables/LogisticNetwork.sol";
import { LogisticDepot, LogisticDepotData } from "./tables/LogisticDepot.sol";
import { LogisticOperation, LogisticOperationData } from "./tables/LogisticOperation.sol";
import { LogisticAction, LogisticActionData } from "./tables/LogisticAction.sol";
import { LogisticTransaction, LogisticTransactionData } from "./tables/LogisticTransaction.sol";
