// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Storage } from "./tables/Storage.sol";
import { Dispenser, DispenserData } from "./tables/Dispenser.sol";
import { DispenserAccess } from "./tables/DispenserAccess.sol";
import { DispenserTribeAccess } from "./tables/DispenserTribeAccess.sol";
import { DispenserAdminAccess } from "./tables/DispenserAdminAccess.sol";
import { DispenserTribeAdminAccess } from "./tables/DispenserTribeAdminAccess.sol";
import { DispenserConfig, DispenserConfigData } from "./tables/DispenserConfig.sol";
import { InventoryItemQ, InventoryItemQData } from "./tables/InventoryItemQ.sol";
