// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IDispenserSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDispenserSystem {
  function Bilkatz__initDispenser(uint256 ssuId) external;

  function Bilkatz__requestDispensation(address playerID, uint256 dispenserID) external;

  function Bilkatz__configureDispenser(uint256 dispenserID, bool repeatable, uint256[] memory stackIds) external;

  function Bilkatz__addStacksToDispenser(uint256 dispenserID, uint256[] memory stackIds) external;

  function Bilkatz__itemParamsToStackIds(InventoryItemParams[] memory items) external returns (uint256[] memory);

  function Bilkatz__StackIdsToItemParams(
    uint256[] memory stackIds
  ) external view returns (InventoryItemParams[] memory);

  function Bilkatz__setPlayerAccess(address playerID, uint256 dispenserID, bool hasAccessFlag) external;

  function Bilkatz__setTribeAccess(uint256 tribeID, uint256 dispenserID, bool hasAccessFlag) external;

  function Bilkatz__setPlayerAdminAccess(address playerID, bool hasAdminAccessFlag) external;

  function Bilkatz__setTribeAdminAccess(uint256 tribeID, bool hasAdminAccessFlag) external;
}
