// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticAgentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticAgentSystem {
  function AWAR__createLogisticAgent(address smartCharacterAddress, uint256 operationId) external returns (uint256);

  function AWAR__deleteLogisticAgent(uint256 agentId) external;
}
