// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticProviderSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticProviderSystem {
  function AWAR__createLogisticProvider(address smartCharacterAddress) external returns (uint256);

  function AWAR__deleteLogisticProvider(uint256 providerId) external;
}
