// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticDepotSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticDepotSystem {
  function AWAR__createLogisticDepot(
    uint256 providerId,
    string memory codename,
    uint256 smartStorageUnitId
  ) external returns (uint256);

  function AWAR__editDepotCodename(uint256 depotId, string memory newCodename) external;

  function AWAR__deleteLogisticDepot(uint256 depotId) external;
}
