// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LogisticFixtureType } from "@store/common.sol";

/**
 * @title ILogisticFixtureSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticFixtureSystem {
  function AWAR__createLogisticFixture(
    uint256 providerId,
    string memory codename,
    LogisticFixtureType fixtureType
  ) external returns (uint256);

  function AWAR__editFixtureCodename(uint256 fixtureId, string memory newCodename) external;

  function AWAR__deleteLogisticFixture(uint256 fixtureId) external;
}
