// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "@eveworld/world-v2/src/namespaces/evefrontier/systems/inventory/types.sol";

/**
 * @title IStorageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStorageSystem {
  function Bilkatz__initStorage(uint256 ssuId) external;

  function Bilkatz__requestItem(uint256 objektId, InventoryItemParams[] memory items) external;
}
