// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITaskSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITaskSystem {
  function TASK__createTask(
    address assignee,
    string memory description,
    uint256 deadline
  ) external returns (bytes32 taskId);

  function TASK__updateTaskAssignee(bytes32 taskId, address newAssignee) external;

  function TASK__updateTaskDeadline(bytes32 taskId, uint256 newDeadline) external;

  function TASK__updateTaskDescription(bytes32 taskId, string memory newDescription) external;

  function TASK__completeTask(bytes32 taskId) external;
}
