// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/LogisticClearance/types.sol";

/**
 * @title IClearanceVerifierSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClearanceVerifierSystem {
  function AWAR__verifyClearance(ProofArgs calldata proof) external view returns (bool);

  function AWAR__verifyClearanceAttributes(ProofArgs calldata proof) external view returns (bool);

  function AWAR__verifyPubSignalKnownConstants(ProofArgs calldata proof) external pure returns (bool);
}
