// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticCoordinatorSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticCoordinatorSystem {
  function AWAR__createLogisticCoordinator(address smartCharacterAddress, uint256 networkId) external returns (uint256);

  function AWAR__deleteLogisticCoordinator(uint256 coordinatorId) external;
}
