// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/types.sol";

/**
 * @title ILogisticDepotSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticDepotSystem {
  function AWAR__createLogisticDepot(ProofArgs memory proof, uint256 smartStorageUnitId) external returns (uint256);

  function AWAR__deleteLogisticDepot(ProofArgs memory proof, uint256 depotId) external;

  function AWAR__addDepotNetwork(ProofArgs memory proof, uint256 depotId, uint256 networkId) external;

  function AWAR__removeDepotNetwork(ProofArgs memory proof, uint256 depotId, uint256 networkId) external;
}
