// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/LogisticClearance/types.sol";
import { LogisticActionType } from "@store/common.sol";

/**
 * @title ILogisticActionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticActionSystem {
  function AWAR__createLogisticAction(
    ProofArgs memory proof,
    LogisticActionType actionType,
    uint256 actionItemId,
    uint256 actionItemAmount,
    uint256 sourceDepotId,
    uint256 destinationDepotId,
    uint256 operationId
  ) external returns (uint256);

  function AWAR__deleteLogisticAction(ProofArgs memory proof, uint256 actionId) external;

  function AWAR__editActionType(ProofArgs memory proof, uint256 actionId, LogisticActionType newActionType) external;

  function AWAR__editActionSourceDepot(ProofArgs memory proof, uint256 actionId, uint256 newSourceDepotId) external;

  function AWAR__editActionDestinationDepot(
    ProofArgs memory proof,
    uint256 actionId,
    uint256 newDestinationDepotId
  ) external;

  function AWAR__editActionItemId(ProofArgs memory proof, uint256 actionId, uint256 newActionItemId) external;

  function AWAR__editActionItemAmount(ProofArgs memory proof, uint256 actionId, uint256 newActionItemAmount) external;
}
