// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/LogisticClearance/types.sol";

/**
 * @title ILogisticNetworkSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticNetworkSystem {
  function AWAR__createLogisticNetwork(ProofArgs memory proof, string memory name) external returns (uint256);

  function AWAR__deleteLogisticNetwork(ProofArgs memory proof, uint256 networkId) external;

  function AWAR__editNetworkName(ProofArgs memory proof, uint256 networkId, string memory newName) external;

  function AWAR__addNetworkDepot(ProofArgs memory proof, uint256 networkId, uint256 depotId) external;

  function AWAR__removeNetworkDepot(ProofArgs memory proof, uint256 networkId, uint256 depotId) external;
}
