// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticNetworkSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticNetworkSystem {
  function AWAR__createLogisticNetwork(
    string memory name,
    uint256 providerId,
    uint256[] memory coordinatorIds
  ) external returns (uint256);

  function AWAR__deleteLogisticNetwork(uint256 networkId) external;

  function AWAR__editNetworkName(uint256 networkId, string memory newName) external;

  function AWAR__transferNetworkOwnership(uint256 networkId, uint256 newNetworkProviderId) external;

  function AWAR__addNetworkCoordinator(uint256 networkId, uint256 coordinatorId) external;

  function AWAR__removeNetworkCoordinator(uint256 networkId, uint256 coordinatorId) external;
}
