// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LogisticDepotType } from "@store/common.sol";

/**
 * @title ILogisticDepotSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticDepotSystem {
  function AWAR__createLogisticDepot(
    uint256 smartStorageUnitId,
    LogisticDepotType depotType,
    uint256[] memory networkIds
  ) external returns (uint256);

  function AWAR__deleteLogisticDepot(uint256 depotId) external;

  function AWAR__editDepotType(uint256 depotId, LogisticDepotType newDepotType) external;

  function AWAR__addDepotNetwork(uint256 depotId, uint256 networkId) external;

  function AWAR__removeDepotNetwork(uint256 depotId, uint256 networkId) external;
}
