// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticOperationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticOperationSystem {
  function AWAR__createLogisticOperation(
    string memory codename,
    uint256 coordinatorId,
    uint256[] memory agentIds
  ) external returns (uint256);

  function AWAR__deleteLogisticOperation(uint256 operationId) external;

  function AWAR__transferOperationalControl(uint256 operationId, uint256 newCoordinatorId) external;

  function AWAR__addOperationAgent(uint256 operationId, uint256 agentId) external;

  function AWAR__removeOperationAgent(uint256 operationId, uint256 agentId) external;
}
