// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/types.sol";
import { LogisticTransactionType } from "@store/common.sol";

/**
 * @title ILogisticTransactionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticTransactionSystem {
  function AWAR__createLogisticTransaction(
    ProofArgs memory proof,
    LogisticTransactionType transactionType,
    uint256 transactionItemId,
    uint256 transactionItemAmount,
    address agent,
    uint256 depotId,
    uint256 actionId
  ) external returns (uint256);
}
