// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProofArgs } from "@systems/types.sol";

/**
 * @title ILogisticOperationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticOperationSystem {
  function AWAR__createLogisticOperation(
    ProofArgs memory proof,
    string memory codename,
    address coordinator,
    uint256 networkId
  ) external returns (uint256);

  function AWAR__deleteLogisticOperation(ProofArgs memory proof, uint256 operationId) external;

  function AWAR__transferOperationalControl(
    ProofArgs memory proof,
    uint256 operationId,
    address newCoordinatorId
  ) external;
}
