// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILogisticNetworkSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILogisticNetworkSystem {
  function AWAR__createLogisticNetwork(
    uint256 providerId,
    string memory codename,
    uint256[] memory depotIds,
    uint256[] memory fixtureIds,
    uint256[] memory coordinatorIds
  ) external returns (uint256);

  function AWAR__deleteLogisticNetwork(uint256 networkId) external;

  function AWAR__editNetworkCodename(uint256 networkId, string memory newCodename) external;

  function AWAR__transferNetworkOwnership(uint256 networkId, uint256 newNetworkProviderId) external;

  function AWAR__addNetworkCoordinator(uint256 networkId, uint256 coordinatorId) external;

  function AWAR__removeNetworkCoordinator(uint256 networkId, uint256 coordinatorId) external;

  function AWAR__addNetworkDepot(uint256 networkId, uint256 depotId) external;

  function AWAR__removeNetworkDepot(uint256 networkId, uint256 depotId) external;

  function AWAR__addNetworkFixture(uint256 networkId, uint256 fixtureId) external;

  function AWAR__removeNetworkFixture(uint256 networkId, uint256 fixtureId) external;
}
