// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { ILogisticAgentSystem } from "./ILogisticAgentSystem.sol";
import { ILogisticCoordinatorSystem } from "./ILogisticCoordinatorSystem.sol";
import { ILogisticProviderSystem } from "./ILogisticProviderSystem.sol";
import { ILogisticActionSystem } from "./ILogisticActionSystem.sol";
import { ILogisticOperationSystem } from "./ILogisticOperationSystem.sol";
import { ILogisticTransactionSystem } from "./ILogisticTransactionSystem.sol";
import { ILogisticDepotSystem } from "./ILogisticDepotSystem.sol";
import { ILogisticFixtureSystem } from "./ILogisticFixtureSystem.sol";
import { ILogisticNetworkSystem } from "./ILogisticNetworkSystem.sol";
import { ILogisticSystem } from "./ILogisticSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  ILogisticAgentSystem,
  ILogisticCoordinatorSystem,
  ILogisticProviderSystem,
  ILogisticActionSystem,
  ILogisticOperationSystem,
  ILogisticTransactionSystem,
  ILogisticDepotSystem,
  ILogisticFixtureSystem,
  ILogisticNetworkSystem,
  ILogisticSystem
{}
